///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CityLocalNames {
/*
{
  "ascii": "Gia Lai",
  "en": "Gia Lai",
  "feature_name": "Tỉnh Gia Lai"
} 
*/

  String? ascii;
  String? en;
  String? featureName;

  CityLocalNames({
    this.ascii,
    this.en,
    this.featureName,
  });
  CityLocalNames.fromJson(Map<String, dynamic> json) {
    ascii = json["ascii"]?.toString();
    en = json["en"]?.toString();
    featureName = json["feature_name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["ascii"] = ascii;
    data["en"] = en;
    data["feature_name"] = featureName;
    return data;
  }
}

class City {
/*
{
  "name": "Tỉnh Gia Lai",
  "local_names": {
    "ascii": "Gia Lai",
    "en": "Gia Lai",
    "feature_name": "Tỉnh Gia Lai"
  },
  "lat": 13.75,
  "lon": 108.25,
  "country": "VN"
} 
*/

  String? name;
  CityLocalNames? localNames;
  double? lat;
  double? lon;
  String? country;

  City({
    this.name,
    this.localNames,
    this.lat,
    this.lon,
    this.country,
  });
  City.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    localNames = (json["local_names"] != null)
        ? CityLocalNames.fromJson(json["local_names"])
        : null;
    lat = json["lat"]?.toDouble();
    lon = json["lon"]?.toDouble();
    country = json["country"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    if (localNames != null) {
      data["local_names"] = localNames!.toJson();
    }
    data["lat"] = lat;
    data["lon"] = lon;
    data["country"] = country;
    return data;
  }
}
