///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WeatherResponceSys {
/*
{
  "country": "VN",
  "sunrise": 1630535741,
  "sunset": 1630580296
} 
*/

  String? country;
  int? sunrise;
  int? sunset;

  WeatherResponceSys({
    this.country,
    this.sunrise,
    this.sunset,
  });
  WeatherResponceSys.fromJson(Map<String, dynamic> json) {
    country = json["country"]?.toString();
    sunrise = json["sunrise"]?.toInt();
    sunset = json["sunset"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["country"] = country;
    data["sunrise"] = sunrise;
    data["sunset"] = sunset;
    return data;
  }
}

class WeatherResponceClouds {
/*
{
  "all": 100
} 
*/

  int? all;

  WeatherResponceClouds({
    this.all,
  });
  WeatherResponceClouds.fromJson(Map<String, dynamic> json) {
    all = json["all"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["all"] = all;
    return data;
  }
}

class WeatherResponceWind {
/*
{
  "speed": 1.01,
  "deg": 11,
  "gust": 0.93
} 
*/

  double? speed;
  int? deg;
  double? gust;

  WeatherResponceWind({
    this.speed,
    this.deg,
    this.gust,
  });
  WeatherResponceWind.fromJson(Map<String, dynamic> json) {
    speed = json["speed"]?.toDouble();
    deg = json["deg"]?.toInt();
    gust = json["gust"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["speed"] = speed;
    data["deg"] = deg;
    data["gust"] = gust;
    return data;
  }
}

class WeatherResponceMain {
/*
{
  "temp": 295.34,
  "feels_like": 296.12,
  "temp_min": 295.34,
  "temp_max": 295.34,
  "pressure": 1010,
  "humidity": 96,
  "sea_level": 1010,
  "grnd_level": 953
} 
*/

  double? temp;
  double? feelsLike;
  double? tempMin;
  double? tempMax;
  int? pressure;
  int? humidity;
  int? seaLevel;
  int? grndLevel;

  WeatherResponceMain({
    this.temp,
    this.feelsLike,
    this.tempMin,
    this.tempMax,
    this.pressure,
    this.humidity,
    this.seaLevel,
    this.grndLevel,
  });
  WeatherResponceMain.fromJson(Map<String, dynamic> json) {
    temp = json["temp"]?.toDouble();
    feelsLike = json["feels_like"]?.toDouble();
    tempMin = json["temp_min"]?.toDouble();
    tempMax = json["temp_max"]?.toDouble();
    pressure = json["pressure"]?.toInt();
    humidity = json["humidity"]?.toInt();
    seaLevel = json["sea_level"]?.toInt();
    grndLevel = json["grnd_level"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["temp"] = temp;
    data["feels_like"] = feelsLike;
    data["temp_min"] = tempMin;
    data["temp_max"] = tempMax;
    data["pressure"] = pressure;
    data["humidity"] = humidity;
    data["sea_level"] = seaLevel;
    data["grnd_level"] = grndLevel;
    return data;
  }
}

class WeatherResponceWeather {
/*
{
  "id": 804,
  "main": "Clouds",
  "description": "overcast clouds",
  "icon": "04n"
} 
*/

  int? id;
  String? main;
  String? description;
  String? icon;

  WeatherResponceWeather({
    this.id,
    this.main,
    this.description,
    this.icon,
  });
  WeatherResponceWeather.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    main = json["main"]?.toString();
    description = json["description"]?.toString();
    icon = json["icon"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["main"] = main;
    data["description"] = description;
    data["icon"] = icon;
    return data;
  }
}

class WeatherResponceCoord {
/*
{
  "lon": 108.25,
  "lat": 13.75
} 
*/

  double? lon;
  double? lat;

  WeatherResponceCoord({
    this.lon,
    this.lat,
  });
  WeatherResponceCoord.fromJson(Map<String, dynamic> json) {
    lon = json["lon"]?.toDouble();
    lat = json["lat"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["lon"] = lon;
    data["lat"] = lat;
    return data;
  }
}

class WeatherResponce {
/*
{
  "coord": {
    "lon": 108.25,
    "lat": 13.75
  },
  "weather": [
    {
      "id": 804,
      "main": "Clouds",
      "description": "overcast clouds",
      "icon": "04n"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 295.34,
    "feels_like": 296.12,
    "temp_min": 295.34,
    "temp_max": 295.34,
    "pressure": 1010,
    "humidity": 96,
    "sea_level": 1010,
    "grnd_level": 953
  },
  "visibility": 10000,
  "wind": {
    "speed": 1.01,
    "deg": 11,
    "gust": 0.93
  },
  "clouds": {
    "all": 100
  },
  "dt": 1630596345,
  "sys": {
    "country": "VN",
    "sunrise": 1630535741,
    "sunset": 1630580296
  },
  "timezone": 25200,
  "id": 1581088,
  "name": "Gia Lai",
  "cod": 200
} 
*/

  WeatherResponceCoord? coord;
  List<WeatherResponceWeather?>? weather;
  String? base;
  WeatherResponceMain? main;
  int? visibility;
  WeatherResponceWind? wind;
  WeatherResponceClouds? clouds;
  int? dt;
  WeatherResponceSys? sys;
  int? timezone;
  int? id;
  String? name;
  int? cod;

  WeatherResponce({
    this.coord,
    this.weather,
    this.base,
    this.main,
    this.visibility,
    this.wind,
    this.clouds,
    this.dt,
    this.sys,
    this.timezone,
    this.id,
    this.name,
    this.cod,
  });
  WeatherResponce.fromJson(Map<String, dynamic> json) {
    coord = (json["coord"] != null) ? WeatherResponceCoord.fromJson(json["coord"]) : null;
  if (json["weather"] != null) {
  final v = json["weather"];
  final arr0 = <WeatherResponceWeather>[];
  v.forEach((v) {
  arr0.add(WeatherResponceWeather.fromJson(v));
  });
    weather = arr0;
    }
    base = json["base"]?.toString();
    main = (json["main"] != null) ? WeatherResponceMain.fromJson(json["main"]) : null;
    visibility = json["visibility"]?.toInt();
    wind = (json["wind"] != null) ? WeatherResponceWind.fromJson(json["wind"]) : null;
    clouds = (json["clouds"] != null) ? WeatherResponceClouds.fromJson(json["clouds"]) : null;
    dt = json["dt"]?.toInt();
    sys = (json["sys"] != null) ? WeatherResponceSys.fromJson(json["sys"]) : null;
    timezone = json["timezone"]?.toInt();
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    cod = json["cod"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (coord != null) {
      data["coord"] = coord!.toJson();
    }
    if (weather != null) {
      final v = weather;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["weather"] = arr0;
    }
    data["base"] = base;
    if (main != null) {
      data["main"] = main!.toJson();
    }
    data["visibility"] = visibility;
    if (wind != null) {
      data["wind"] = wind!.toJson();
    }
    if (clouds != null) {
      data["clouds"] = clouds!.toJson();
    }
    data["dt"] = dt;
    if (sys != null) {
      data["sys"] = sys!.toJson();
    }
    data["timezone"] = timezone;
    data["id"] = id;
    data["name"] = name;
    data["cod"] = cod;
    return data;
  }
}
